server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: lb://auth-service
            predicates:
              - Path=/api/auth/**
            filters:
              - RewritePath=/api/auth/v3/api-docs, /v3/api-docs
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/users/**, /api/vehicles/**
            filters:
              - RewritePath=/api/users/v3/api-docs, /v3/api-docs
          - id: parking-service
            uri: lb://parking-service
            predicates:
              - Path=/api/parking/**
            filters:
              - RewritePath=/api/parking/v3/api-docs, /v3/api-docs
          - id: booking-service
            uri: lb://booking-service
            predicates:
              - Path=/api/bookings/**
            filters:
              - RewritePath=/api/bookings/v3/api-docs, /v3/api-docs
          - id: payment-service
            uri: lb://payment-service
            predicates:
              - Path=/api/payments/**
            filters:
              - RewritePath=/api/payments/v3/api-docs, /v3/api-docs


springdoc:
  swagger-ui:
    urls:
      - name: auth-service
        url: /api/auth/v3/api-docs
      - name: user-service
        url: /api/users/v3/api-docs
      - name: parking-service
        url: /api/parking/v3/api-docs
      - name: booking-service
        url: /api/bookings/v3/api-docs
      - name: payment-service
        url: /api/payments/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  public-key: ${JWT_PUBLIC_KEY:}
