server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: lb://auth-service
            predicates:
              - Path=/api/auth/**
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/api/users/**, /api/vehicles/**
          - id: parking-service
            uri: lb://parking-service
            predicates:
              - Path=/api/parking/**
          - id: booking-service
            uri: lb://booking-service
            predicates:
              - Path=/api/bookings/**
          - id: payment-service
            uri: lb://payment-service
            predicates:
              - Path=/api/payments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  public-key: ""
